### ISSUE TITLE
Missing `PRIMARY_SITE_URL` throwing exception

### ISSUE THREAD

**Issue by bencroker** [szenario-fordesigners/spacecontrol#10]
I’ve enabled email notifications in version 1.2.0 of the plugin. I don’t have `PRIMARY_SITE_URL` set in my `.env` file and this appears to be causing an exception to be thrown when the `SpaceControl Disk Usage Check` queue job runs.

Here’s the stack trace:

```
2023-11-23 16:34:20 [queue.ERROR] [craft\queue\QueueLogBehavior::afterError]  [57260] SpaceControl Disk Usage Check (attempt: 1, pid: 11) - Error (time: 0.892s): Undefined array key 1 {"memory":8320936} 
2023-11-23 16:34:20 [queue.ERROR] [yii\base\ErrorException:2] yii\base\ErrorException: Undefined array key 1 in /var/www/project/cms_v4/vendor/szenario/craft-spacecontrol/src/NotificationService/NotificationService.php:85
Stack trace:
#0 /var/www/project/cms_v4/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/var/www/projec...', 85)
#1 /var/www/project/cms_v4/vendor/szenario/craft-spacecontrol/src/NotificationService/NotificationService.php(85): craft\web\ErrorHandler->handleError(2, 'Undefined array...', '/var/www/projec...', 85)
#2 /var/www/project/cms_v4/vendor/szenario/craft-spacecontrol/src/NotificationService/NotificationService.php(110): szenario\craftspacecontrol\NotificationService\NotificationService::notificationTemplate(91, '978915008', '1')
#3 /var/www/project/cms_v4/vendor/szenario/craft-spacecontrol/src/NotificationService/NotificationService.php(72): szenario\craftspacecontrol\NotificationService\NotificationService::sendNotifications(Object(szenario\craftspacecontrol\models\Settings))
#4 /var/www/project/cms_v4/vendor/szenario/craft-spacecontrol/src/jobs/SpaceControlChecker.php(17): szenario\craftspacecontrol\NotificationService\NotificationService::start()
#5 /var/www/project/cms_v4/vendor/yiisoft/yii2-queue/src/Queue.php(243): szenario\craftspacecontrol\jobs\SpaceControlChecker->execute(Object(craft\queue\Queue))
#6 /var/www/project/cms_v4/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('57260', 'O:51:"szenario\\...', '30', 1)
#7 /var/www/project/cms_v4/vendor/craftcms/cms/src/queue/Queue.php(190): yii\queue\cli\Queue->handleMessage('57260', 'O:51:"szenario\\...', '30', 1)
#8 /var/www/project/cms_v4/vendor/craftcms/cms/src/queue/Queue.php(165): craft\queue\Queue->executeJob()
#9 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#10 /var/www/project/cms_v4/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#11 /var/www/project/cms_v4/vendor/craftcms/cms/src/queue/Queue.php(173): yii\queue\cli\Queue->runWorker(Object(Closure))
#12 /var/www/project/cms_v4/vendor/craftcms/cms/src/controllers/QueueController.php(82): craft\queue\Queue->run()
#13 [internal function]: craft\controllers\QueueController->actionRun()
#14 /var/www/project/cms_v4/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/project/cms_v4/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/project/cms_v4/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('run', Array)
#17 /var/www/project/cms_v4/vendor/craftcms/cms/src/web/Application.php(305): yii\base\Module->runAction('queue/run', Array)
#18 /var/www/project/cms_v4/vendor/craftcms/cms/src/web/Application.php(606): craft\web\Application->runAction('queue/run', Array)
#19 /var/www/project/cms_v4/vendor/craftcms/cms/src/web/Application.php(284): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /var/www/project/cms_v4/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /var/www/project/cms_v4/web/index.php(15): yii\base\Application->run()
#22 {main} {"memory":8321368,"exception":"[object] (yii\\base\\ErrorException(code: 2): Undefined array key 1 at /var/www/project/cms_v4/vendor/szenario/craft-spacecontrol/src/NotificationService/NotificationService.php:85)"} 
```

**Comment by thomasbendl** [comment]
Thx for the hint @bencroker! The fixed Version ist out in release [v1.2.1.1](https://github.com/szenario-fordesigners/spacecontrol/releases/tag/1.2.1.1)
